// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeManagement.Infrastructure.Persistence.DbContexts;

#nullable disable

namespace RecipeManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418004746_ProcessSegmentProductSegment")]
    partial class ProcessSegmentProductSegment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeManagement.Domain.MaterialDefinitions.Aggregates.MaterialDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MaterialDefinitions", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Domain.MaterialDefinitions.Entities.MaterialDefinitionProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaterialDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialDefinitionId");

                    b.ToTable("MaterialDefinitionProperties", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProcessSegments.Aggregates.ProcessSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProcessSegments", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProcessSegments.Entities.ProcessSegmentParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("ProcessSegmentParameters", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProductSegments.Aggregates.ProductSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProcessSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaterialDefinitionId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("ProductSegments", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProductSegments.Entities.ProductSegmentParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessSegmentParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessSegmentParameterId");

                    b.HasIndex("ProductSegmentId");

                    b.ToTable("ProductSegmentParameters", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Infrastructure.Persistence.Entities.IntegrationOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOnUtc");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_IntegrationOutbox_Unprocessed")
                        .HasFilter("[ProcessedAtUtc] IS NULL");

                    b.ToTable("IntegrationOutboxMessages", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Infrastructure.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_ProcessedAtUtc_Null")
                        .HasFilter("[ProcessedAtUtc] IS NULL");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("RecipeManagement.Domain.MaterialDefinitions.Entities.MaterialDefinitionProperty", b =>
                {
                    b.HasOne("RecipeManagement.Domain.MaterialDefinitions.Aggregates.MaterialDefinition", "MaterialDefinition")
                        .WithMany("Properties")
                        .HasForeignKey("MaterialDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialDefinition");
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProcessSegments.Entities.ProcessSegmentParameter", b =>
                {
                    b.HasOne("RecipeManagement.Domain.ProcessSegments.Aggregates.ProcessSegment", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProductSegments.Aggregates.ProductSegment", b =>
                {
                    b.HasOne("RecipeManagement.Domain.MaterialDefinitions.Aggregates.MaterialDefinition", "MaterialDefinition")
                        .WithMany("ProductSegments")
                        .HasForeignKey("MaterialDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeManagement.Domain.ProcessSegments.Aggregates.ProcessSegment", "ProcessSegment")
                        .WithMany("ProductSegments")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialDefinition");

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProductSegments.Entities.ProductSegmentParameter", b =>
                {
                    b.HasOne("RecipeManagement.Domain.ProcessSegments.Entities.ProcessSegmentParameter", null)
                        .WithMany("ProductSegmentParameters")
                        .HasForeignKey("ProcessSegmentParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeManagement.Domain.ProductSegments.Aggregates.ProductSegment", "ProductSegment")
                        .WithMany("Parameters")
                        .HasForeignKey("ProductSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSegment");
                });

            modelBuilder.Entity("RecipeManagement.Domain.MaterialDefinitions.Aggregates.MaterialDefinition", b =>
                {
                    b.Navigation("ProductSegments");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProcessSegments.Aggregates.ProcessSegment", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("ProductSegments");
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProcessSegments.Entities.ProcessSegmentParameter", b =>
                {
                    b.Navigation("ProductSegmentParameters");
                });

            modelBuilder.Entity("RecipeManagement.Domain.ProductSegments.Aggregates.ProductSegment", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
