name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all tags to ensure the check is accurate
      
      - name: Get Version
        id: get_v
        run: |
          VERSION=$(grep -oPm1 '(?<=<Version>)[^<]+' Directory.Build.props)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if Tag exists
        id: check_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if the tag exists in the remote repository
          if gh release view "v${{ steps.get_v.outputs.VERSION }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Release v${{ steps.get_v.outputs.VERSION }} already exists. Skipping."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        # Only run if the 'exists' output from the previous step is 'false'
        if: steps.check_tag.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.get_v.outputs.VERSION }}" \
            --title "Release v${{ steps.get_v.outputs.VERSION }}" \
            --generate-notes